import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "../_components/Navbar/Navbar";
import MySessionProvider from "../MySessionProvider/MySessionProvider";
import CartContextProvider from "@/src/context/CartContext";
import WishlistContextProvider from "../context/wishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FrechCart App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <CartContextProvider>
              
              <Toaster/>
            <WishlistContextProvider>
              <Navbar/>
              {children}
            </WishlistContextProvider>
          </CartContextProvider>
       
        </MySessionProvider>
       
      </body>
    </html>
  );
}
